from __future__ import annotations

import json
import sqlite3
from datetime import datetime, timezone
from pathlib import Path
from typing import Protocol
from uuid import UUID

from app.db.models import (
    AgentOutput,
    AlertRecord,
    AlertResponseRecord,
    ArmedSetup,
    AutonomyLog,
    BacktestStat,
    CalibrationSuggestion,
    CatalogSymbol,
    DatabaseMaintenanceEvent,
    DecisionMemory,
    DerivativeDataSnapshot,
    DerivativeMetric,
    EngineParamVersion,
    EntryIntent,
    EntryScenario,
    JudgmentLedgerEntry,
    JudgmentScore,
    InstrumentMap,
    LiquidationEvent,
    MarketCandle,
    MarketSnapshotRecord,
    MonitoringLog,
    Position,
    PositionEvent,
    PositionInsight,
    PositionSnapshot,
    PositionStatus,
    PaperTrade,
    Report,
    ResearchRun,
    ScoutSnapshot,
    ShadowProfile,
    Trade,
    UniverseDiscovery,
    UserTrade,
    ValidationRun,
    WatchlistItem,
    WhaleEvent,
    WhaleWallet,
)
from app.db.sqlite_utils import SQLITE_WRITE_LOCK, connect_sqlite
from app.db.migrations import run_migrations


class Repository(Protocol):
    def add_report(self, report: Report) -> Report: ...
    def get_report(self, report_id: UUID) -> Report | None: ...
    def latest_report(self, symbol: str) -> Report | None: ...
    def recent_reports(self, limit: int = 8) -> list[Report]: ...
    def add_position(self, position: Position) -> Position: ...
    def list_positions(self, status: PositionStatus | None = None) -> list[Position]: ...
    def get_position(self, position_id: UUID) -> Position | None: ...
    def update_position(self, position: Position) -> Position: ...
    def add_monitoring_log(self, log: MonitoringLog) -> MonitoringLog: ...
    def list_monitoring_logs(self, position_id: UUID, limit: int = 50) -> list[MonitoringLog]: ...
    def add_position_snapshot(self, snapshot: PositionSnapshot) -> PositionSnapshot: ...
    def list_position_snapshots(self, position_id: UUID, limit: int = 50) -> list[PositionSnapshot]: ...
    def add_position_insight(self, insight: PositionInsight) -> PositionInsight: ...
    def list_position_insights(self, position_id: UUID, limit: int = 20) -> list[PositionInsight]: ...
    def add_position_event(self, event: PositionEvent) -> PositionEvent: ...
    def list_position_events(self, position_id: UUID, limit: int = 50) -> list[PositionEvent]: ...
    def add_alert(self, alert: AlertRecord) -> AlertRecord: ...
    def list_alerts(self, position_id: UUID | None = None, limit: int = 100) -> list[AlertRecord]: ...
    def add_alert_response(self, response: AlertResponseRecord) -> AlertResponseRecord: ...
    def get_alert_response(self, alert_id: UUID) -> AlertResponseRecord | None: ...
    def list_alert_responses(
        self,
        position_id: UUID | None = None,
        rule_id: str | None = None,
        limit: int = 200,
    ) -> list[AlertResponseRecord]: ...
    def add_scout_snapshot(self, snapshot: ScoutSnapshot) -> ScoutSnapshot: ...
    def list_scout_snapshots(self, symbol: str | None = None, limit: int = 100) -> list[ScoutSnapshot]: ...
    def latest_scout_snapshot(self, symbol: str, timeframe: str | None = None) -> ScoutSnapshot | None: ...
    def get_directional_state(self, symbol: str, timeframe: str) -> dict | None: ...
    def upsert_directional_state(self, symbol: str, timeframe: str, state: dict) -> bool: ...
    def list_directional_states(self, limit: int = 100) -> list[dict]: ...
    def upsert_armed_setup(self, setup: ArmedSetup) -> ArmedSetup: ...
    def get_armed_setup(self, setup_id: UUID) -> ArmedSetup | None: ...
    def list_armed_setups(self, symbol: str | None = None, status: str | None = None, limit: int = 200) -> list[ArmedSetup]: ...
    def upsert_entry_intent(self, intent: EntryIntent) -> EntryIntent: ...
    def get_entry_intent(self, intent_id: UUID) -> EntryIntent | None: ...
    def list_entry_intents(
        self,
        symbol: str | None = None,
        status: str | None = None,
        limit: int = 200,
    ) -> list[EntryIntent]: ...
    def upsert_backtest_stat(self, stat: BacktestStat) -> BacktestStat: ...
    def list_backtest_stats(
        self,
        symbol: str | None = None,
        signature_key: str | None = None,
        limit: int = 100,
    ) -> list[BacktestStat]: ...
    def upsert_stance_history_candles(
        self,
        symbol: str,
        timeframe: str,
        candles: list[MarketCandle],
        source: str,
        observed_at: datetime,
    ) -> int: ...
    def list_stance_history_candles(
        self,
        symbol: str,
        timeframe: str,
        limit: int = 5000,
    ) -> list[MarketCandle]: ...
    def upsert_universe_discovery(self, discovery: UniverseDiscovery) -> UniverseDiscovery: ...
    def list_universe_discoveries(
        self,
        symbol: str | None = None,
        status: str | None = None,
        limit: int = 100,
    ) -> list[UniverseDiscovery]: ...
    def list_recent_gate_passed_universe_discoveries(self, limit: int = 500) -> list[UniverseDiscovery]: ...
    def add_trade(self, trade: Trade) -> Trade: ...
    def get_trade(self, trade_id: UUID) -> Trade | None: ...
    def list_trades(self) -> list[Trade]: ...
    def upsert_paper_trade(self, trade: PaperTrade) -> PaperTrade: ...
    def get_paper_trade(self, trade_id: UUID) -> PaperTrade | None: ...
    def list_paper_trades(
        self,
        status: str | None = None,
        symbol: str | None = None,
        limit: int = 500,
    ) -> list[PaperTrade]: ...
    def upsert_user_trade(self, trade: UserTrade) -> UserTrade: ...
    def list_user_trades(self, since: datetime | None = None, limit: int = 5000) -> list[UserTrade]: ...
    def upsert_user_account_fill(self, fill: dict) -> bool: ...
    def list_user_account_fills(self, since: datetime | None = None, limit: int = 10000) -> list[dict]: ...
    def get_paper_engine_state(self, symbol: str, timeframe: str) -> dict | None: ...
    def upsert_paper_engine_state(self, symbol: str, timeframe: str, state: dict) -> bool: ...
    def upsert_paper_gate_funnel(self, record: dict) -> bool: ...
    def list_paper_gate_funnel(
        self,
        since: datetime | None = None,
        symbol: str | None = None,
        limit: int = 10000,
    ) -> list[dict]: ...
    def upsert_entry_block_log(self, record: dict) -> bool: ...
    def list_entry_block_logs(
        self,
        since: datetime | None = None,
        symbol: str | None = None,
        failed_gate: str | None = None,
        limit: int = 10000,
    ) -> list[dict]: ...
    def add_judgment(self, judgment: JudgmentLedgerEntry) -> JudgmentLedgerEntry: ...
    def list_judgments(self, position_id: UUID, limit: int = 200) -> list[JudgmentLedgerEntry]: ...
    def add_judgment_score(self, score: JudgmentScore) -> JudgmentScore: ...
    def list_judgment_scores(
        self,
        position_id: UUID | None = None,
        trade_id: UUID | None = None,
        limit: int = 500,
    ) -> list[JudgmentScore]: ...
    def add_calibration_suggestion(self, suggestion: CalibrationSuggestion) -> CalibrationSuggestion: ...
    def get_calibration_suggestion(self, suggestion_id: UUID) -> CalibrationSuggestion | None: ...
    def list_calibration_suggestions(self, status: str | None = None, limit: int = 50) -> list[CalibrationSuggestion]: ...
    def add_engine_param_version(self, version: EngineParamVersion) -> EngineParamVersion: ...
    def latest_engine_param(self, param: str) -> EngineParamVersion | None: ...
    def list_engine_params(self, limit: int = 100) -> list[EngineParamVersion]: ...
    def add_autonomy_log(self, log: AutonomyLog) -> AutonomyLog: ...
    def list_autonomy_logs(
        self,
        signature_key: str | None = None,
        new_state: str | None = None,
        since: datetime | None = None,
        limit: int = 200,
    ) -> list[AutonomyLog]: ...
    def latest_autonomy_states(self) -> dict[str, str]: ...
    def add_market_snapshot(self, snapshot: MarketSnapshotRecord) -> MarketSnapshotRecord: ...
    def add_derivative_snapshot(self, snapshot: DerivativeDataSnapshot) -> DerivativeDataSnapshot: ...
    def list_derivative_snapshots(self, symbol: str | None = None, provider: str | None = None, limit: int = 100) -> list[DerivativeDataSnapshot]: ...
    def latest_derivative_snapshot(self, symbol: str, provider: str | None = None) -> DerivativeDataSnapshot | None: ...
    def delete_derivative_snapshots_before(self, cutoff: datetime) -> int: ...
    def add_derivative_metric(self, metric: DerivativeMetric) -> DerivativeMetric: ...
    def list_derivative_metrics(self, symbol: str | None = None, source: str | None = None, limit: int = 100) -> list[DerivativeMetric]: ...
    def latest_derivative_metric(self, symbol: str, source: str | None = None) -> DerivativeMetric | None: ...
    def delete_derivative_metrics_before(self, cutoff: datetime) -> int: ...
    def add_liquidation_event(self, event: LiquidationEvent) -> LiquidationEvent: ...
    def list_liquidation_events(self, symbol: str | None = None, source: str | None = None, limit: int = 100) -> list[LiquidationEvent]: ...
    def delete_liquidation_events_before(self, cutoff: datetime) -> int: ...
    def add_database_maintenance_event(self, event: DatabaseMaintenanceEvent) -> DatabaseMaintenanceEvent: ...
    def list_database_maintenance_events(self, event_type: str | None = None, limit: int = 50) -> list[DatabaseMaintenanceEvent]: ...
    def add_research_run(self, run: ResearchRun) -> ResearchRun: ...
    def get_research_run(self, run_id: UUID) -> ResearchRun | None: ...
    def list_research_runs(self, symbol: str | None = None, limit: int = 20) -> list[ResearchRun]: ...
    def add_agent_output(self, output: AgentOutput) -> AgentOutput: ...
    def list_agent_outputs(self, research_run_id: UUID) -> list[AgentOutput]: ...
    def add_shadow_profile(self, profile: ShadowProfile) -> ShadowProfile: ...
    def get_shadow_profile(self, shadow_id: str) -> ShadowProfile | None: ...
    def list_shadow_profiles(self, limit: int = 20) -> list[ShadowProfile]: ...
    def add_decision_memory(self, memory: DecisionMemory) -> DecisionMemory: ...
    def list_decision_memories(self, symbol: str | None = None, limit: int = 20) -> list[DecisionMemory]: ...
    def add_validation_run(self, run: ValidationRun) -> ValidationRun: ...
    def get_validation_run(self, run_id: UUID) -> ValidationRun | None: ...
    def list_validation_runs(self, limit: int = 20) -> list[ValidationRun]: ...
    def list_watchlist(self) -> list[WatchlistItem]: ...
    def upsert_watchlist_item(self, item: WatchlistItem) -> WatchlistItem: ...
    def remove_watchlist_item(self, symbol: str) -> bool: ...
    def upsert_instrument_map(self, item: InstrumentMap) -> InstrumentMap: ...
    def get_instrument_map(self, bitget_symbol: str) -> InstrumentMap | None: ...
    def list_instrument_maps(self, status: str | None = None) -> list[InstrumentMap]: ...
    def replace_symbol_catalog(self, symbols: list[CatalogSymbol]) -> int: ...
    def search_symbols(self, query: str, limit: int = 20) -> list[CatalogSymbol]: ...
    def symbol_catalog_updated_at(self) -> datetime | None: ...
    def get_calibration_report_cache(self, report_key: str) -> dict | None: ...
    def upsert_calibration_report_cache(self, report_key: str, payload: dict) -> dict: ...
    def add_entry_scenario(self, scenario: EntryScenario) -> EntryScenario: ...
    def get_entry_scenario(self, scenario_id: UUID) -> EntryScenario | None: ...
    def list_entry_scenarios(self, symbol: str | None = None, limit: int = 50) -> list[EntryScenario]: ...
    def find_matching_scenario(self, symbol: str, direction: str, within_hours: int = 72) -> EntryScenario | None: ...
    def link_scenario_position(self, scenario_id: UUID, position_id: UUID) -> EntryScenario | None: ...
    def upsert_whale_wallet(self, wallet: WhaleWallet) -> WhaleWallet: ...
    def get_whale_wallet(self, address: str) -> WhaleWallet | None: ...
    def list_whale_wallets(self, active: bool | None = None, limit: int = 20) -> list[WhaleWallet]: ...
    def remove_whale_wallet(self, address: str) -> bool: ...
    def add_whale_event(self, event: WhaleEvent) -> bool: ...
    def list_whale_events(
        self,
        symbol: str | None = None,
        wallet_address: str | None = None,
        since: datetime | None = None,
        limit: int = 500,
    ) -> list[WhaleEvent]: ...
    def get_whale_position_state(self, wallet_address: str, coin: str) -> dict | None: ...
    def list_whale_position_states(self, wallet_address: str | None = None, limit: int = 500) -> list[dict]: ...
    def upsert_whale_position_state(self, wallet_address: str, coin: str, state: dict) -> bool: ...
    def delete_whale_position_state(self, wallet_address: str, coin: str) -> bool: ...


class MemoryRepositoryBase:
    def __init__(self) -> None:
        self.reports: dict[UUID, Report] = {}
        self.reports_by_symbol: dict[str, list[UUID]] = {}
        self.positions: dict[UUID, Position] = {}
        self.monitoring_logs: dict[UUID, list[MonitoringLog]] = {}
        self.position_snapshots: dict[UUID, list[PositionSnapshot]] = {}
        self.position_insights: dict[UUID, list[PositionInsight]] = {}
        self.position_events: dict[UUID, list[PositionEvent]] = {}
        self.alerts: dict[UUID, AlertRecord] = {}
        self.alert_responses: dict[UUID, AlertResponseRecord] = {}
        self.scout_snapshots: dict[UUID, ScoutSnapshot] = {}
        self.directional_states: dict[tuple[str, str], dict] = {}
        self.armed_setups: dict[UUID, ArmedSetup] = {}
        self.entry_intents: dict[UUID, EntryIntent] = {}
        self.backtest_stats: dict[UUID, BacktestStat] = {}
        self.stance_history_candles: dict[tuple[str, str, datetime], MarketCandle] = {}
        self.universe_discoveries: dict[UUID, UniverseDiscovery] = {}
        self.trades: dict[UUID, Trade] = {}
        self.paper_trades: dict[UUID, PaperTrade] = {}
        self.user_trades: dict[UUID, UserTrade] = {}
        self.user_account_fills: dict[str, dict] = {}
        self.paper_engine_states: dict[tuple[str, str], dict] = {}
        self.paper_gate_funnel: dict[tuple[str, str, str], dict] = {}
        self.entry_block_logs: dict[str, dict] = {}
        self.judgments: dict[UUID, list[JudgmentLedgerEntry]] = {}
        self.judgment_scores: dict[UUID, JudgmentScore] = {}
        self.calibration_suggestions: dict[UUID, CalibrationSuggestion] = {}
        self.engine_params: dict[UUID, EngineParamVersion] = {}
        self.autonomy_logs: dict[UUID, AutonomyLog] = {}
        self.market_snapshots: dict[UUID, MarketSnapshotRecord] = {}
        self.derivative_snapshots: dict[UUID, DerivativeDataSnapshot] = {}
        self.derivative_metrics: dict[UUID, DerivativeMetric] = {}
        self.liquidation_events: dict[UUID, LiquidationEvent] = {}
        self.database_maintenance_events: dict[UUID, DatabaseMaintenanceEvent] = {}
        self.research_runs: dict[UUID, ResearchRun] = {}
        self.agent_outputs: dict[UUID, list[AgentOutput]] = {}
        self.shadow_profiles: dict[str, ShadowProfile] = {}
        self.decision_memories: dict[UUID, DecisionMemory] = {}
        self.validation_runs: dict[UUID, ValidationRun] = {}
        self.watchlist: dict[str, WatchlistItem] = {}
        self.instrument_maps: dict[str, InstrumentMap] = {}
        self.symbol_catalog: dict[str, CatalogSymbol] = {}
        self.calibration_report_cache: dict[str, dict] = {}
        self.entry_scenarios: dict[UUID, EntryScenario] = {}
        self.whale_wallets: dict[str, WhaleWallet] = {}
        self.whale_events: dict[UUID, WhaleEvent] = {}
        self.whale_position_states: dict[tuple[str, str], dict] = {}


class SQLiteRepositoryBase:
    def __init__(self, database_path: str) -> None:
        self.database_path = database_path
        self._lock = SQLITE_WRITE_LOCK
        Path(database_path).parent.mkdir(parents=True, exist_ok=True)
        self._init_schema()

    def _connect(self) -> sqlite3.Connection:
        return connect_sqlite(self.database_path)

    def _init_schema(self) -> None:
        with self._connect() as connection:
            run_migrations(connection)


def _dump_model(model) -> str:
    return json.dumps(model.model_dump(mode="json"), ensure_ascii=False)


def _json_cache_default(value) -> str:
    if isinstance(value, datetime):
        return value.isoformat()
    if isinstance(value, UUID):
        return str(value)
    raise TypeError(f"Object of type {type(value).__name__} is not JSON serializable")


def _same_directional_bar(current: dict | None, candidate: dict) -> bool:
    """Only a newly confirmed candle may mutate a live hysteresis state."""
    if not isinstance(current, dict) or not isinstance(candidate, dict):
        return False
    current_bar = current.get("last_bar_at")
    candidate_bar = candidate.get("last_bar_at")
    return bool(current_bar and candidate_bar and current_bar == candidate_bar)


def _aware_dt(value: datetime) -> datetime:
    return value if value.tzinfo is not None else value.replace(tzinfo=timezone.utc)


def _timestamp_or_min(value: object) -> datetime:
    if isinstance(value, datetime):
        return _aware_dt(value)
    if isinstance(value, str):
        try:
            return _aware_dt(datetime.fromisoformat(value.replace("Z", "+00:00")))
        except ValueError:
            pass
    return datetime.min.replace(tzinfo=timezone.utc)
